apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: custom-image-builder
spec:
  params:
    - default: 'quay.io/modh/odh-pytorch-notebook@sha256:8bd87f618fe98c714cf34b2540d5560d85fa657c7a64d1b7bdb8ef9201a22df7'
      name: BASE_IMAGE
      type: string
    - default: 'https://github.com/rh-telco-tigers/rhoai-workbench-customizer.git'
      name: GIT_REPO
      type: string
    - default: main
      name: GIT_REVISION
      type: string
    - default: RUN pip install faker; RUN pip install calc
      name: DOCKER_STEPS
      type: string
    - default: rhoai-workbench-customizer
      name: NOTEBOOK_IMAGE_NAME
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: helm-upgrade-from-source
      params:
        - name: charts_dir
          value: helm
        - name: release_version
          value: v1.0.0
        - name: release_name
          value: helm-upgrade-from-source
        - name: release_namespace
          value: redhat-ods-applications
        - name: overwrite_values
          value: 'base_image=$(params.BASE_IMAGE),dockerSteps=$(params.DOCKER_STEPS),notebookImageName=$(params.NOTEBOOK_IMAGE_NAME)'
        - name: values_file
          value: values.yaml
        - name: helm_image
          value: >-
            docker.io/lachlanevenson/k8s-helm@sha256:5c792f29950b388de24e7448d378881f68b3df73a7b30769a6aa861061fd08ae
        - name: upgrade_extra_params
          value: '--debug '
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: helm-upgrade-from-source
      workspaces:
        - name: source
          workspace: workspace
    - name: openshift-client
      params:
        - name: SCRIPT
          value: >-
            oc start-build $(params.NOTEBOOK_IMAGE_NAME)  -n redhat-ods-applications
            --follow
        - name: VERSION
          value: '4.13'
      runAfter:
        - helm-upgrade-from-source
      taskRef:
        kind: Task
        name: openshift-client
  workspaces:
    - name: workspace
  resources: []
  finally: []
