apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    opendatahub.io/notebook-image-creator: pipeline
    opendatahub.io/notebook-image-desc: ""
    opendatahub.io/notebook-image-name: {{ .Values.notebookImageName }}
    opendatahub.io/notebook-image-url: {{ .Values.base_image }}
    opendatahub.io/recommended-accelerators: '[]'
    meta.helm.sh/release-name: helm-release
    meta.helm.sh/release-namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/created-by: pipeline
    opendatahub.io/dashboard: "true"
    opendatahub.io/notebook-image: "true"
    app.kubernetes.io/managed-by: Helm
  name: {{ .Values.notebookImageName }}
  namespace: redhat-ods-applications
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      opendatahub.io/notebook-python-dependencies: '[]'
      opendatahub.io/notebook-software: '[]'
      openshift.io/imported-from: {{ .Values.base_image }}
    from:
      kind: DockerImage
      name: {{ .Values.base_image }}
    generation: 2
    importPolicy:
      importMode: Legacy
    name: {{ .Values.notebookImageName }}
    referencePolicy:
      type: Source
